{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Open Tracker\n",
    "\n",
    "**Project Requirement**\n",
    "https://media-net.github.io/recruitment-open-tracker/\n",
    "\n",
    "\n",
    "**Project Solution **\n",
    "\n",
    "## Solution 1 : With Laravel/Lumen, Mysql\n",
    "\n",
    "The source code is already present. They have aready achive some benchmark.\n",
    "But what we can do,  we can enhance this application as per our need;\n",
    "\n",
    "**summary of Source code**\n",
    "\n",
    " - MailTracker will hook into all outgoing emails from Laravel/Lumen and inject a tracking code into it.\n",
    " - It will also store the rendered email in the database. There is also an interface to view sent emails.\n",
    " - https://github.com/jdavidbakr/mail-tracker\n",
    "\n",
    "**Install Lumen Via Composer**\n",
    "\n",
    "  - composer require jdavidbakr/mail-tracker ~2.1\n",
    "\n",
    "\n",
    "**Additional code can add at**\n",
    "  - jdavidbakr\\MailTracker\\Events\\EmailSentEvent\n",
    "  - jdavidbakr\\MailTracker\\Events\\ViewEmailEvent\n",
    "  - jdavidbakr\\MailTracker\\Events\\LinkClickedEvent\n",
    "\n",
    "\n",
    "**Reference Link **\n",
    "\n",
    "- https://laracasts.com/discuss/channels/laravel/new-package-for-email-tracking\n",
    "- https://packagist.org/packages/jdavidbakr/mail-tracker\n",
    "\n",
    "\n",
    "## Solution 2 :  Simple Code by using PHP, Mysql\n",
    "\n",
    "\n",
    "**How To Run**\n",
    " -  Below url need to run manualy \n",
    " \n",
    "  http://Your-website/Open_tracker/trackersendmail.php\n",
    "\n",
    " - Below url need not to run manualy, as it will run atuomaticaly when email get open clicked\n",
    " \n",
    " http://Your-website/Open_tracker/trackonline.php?src=email&subscriberID=nisha.sonawane@gmail.com&campaignID=6788\n",
    " \n",
    "\n",
    "\n",
    "\n",
    "## Functional Files \n",
    "\n",
    "**Tech Stack **\n",
    " - PHP, Mysql\n",
    "\n",
    "\n",
    "#### Files\n",
    "\n",
    "  - 1) **dbconfig.php**  \n",
    "        This file contain database connection parameters.\n",
    "  - 2) **trackersendmail.php**\n",
    "        This file contain static Email send functionality. If you want dynamic then we can add html form & post form Functionality.\n",
    "  - 4) **trackonline.php**\n",
    "        This File contain the email campaign they've opened and the subscription ID - you saved that from your script\n",
    "  - 5) **classes/EmailTracker.php**\n",
    "        Initialize the EmailCampaign. In this class, we are also connecting to the MySQL server.  In a larger project, connections would be managed by a separate Database abstraction class\n",
    "  - 6) **classes/Email.php**\n",
    "        It contains the information that the Courier & needs to send an email message to a recipient\n",
    "  - 7) **classes/Courier.php**\n",
    "        This class emails converts and emails data from the Email class & It takes an Email and uses the mail() function to send it out\n",
    "\n",
    "**External Files**\n",
    "\n",
    "  - 1) PHPMailer/PHPMailer.php\n",
    "  - 2) images/phpmailer.png\n",
    "  - 3) css/style.css\n",
    "  - 4) js/myjs.js\n",
    "\n",
    "\n",
    "\n",
    "**Database**\n",
    "\n",
    " - Create database test_db;\n",
    "\n",
    " - Use test_db;\n",
    "\n",
    " - CREATE TABLE EmailTracker (\n",
    "    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,\n",
    "    campaignID int(10),\n",
    "    subscriptionID varchar(100),\n",
    "    timestamp TIMESTAMP DEFAULT NOW()\n",
    "   );\n",
    "\n",
    "\n",
    "**To avoid duplicate entry from Table**\n",
    "\n",
    "  - You can write cron job/script & it can schedule as per your need & script should contain below Delete Query.\n",
    "  \n",
    "  - DELETE FROM EmailTracker WHERE id NOT IN(SELECT id FROM (SELECT max(id) as id FROM EmailTracker GROUP By subscriptionID) as p2)\n",
    "\n",
    "  - If you want to see the data before you delete(what will be left) then use below query\n",
    "\n",
    "  -  SELECT *  FROM EmailTracker WHERE id NOT IN(SELECT id FROM (SELECT max(id) as id FROM EmailTracker GROUP By subscriptionID) as p2)\n",
    " \n",
    "  - Why Cron Job?\n",
    "     -  We can Check duplicate rows at every tracker(EmailTracker.php), but it will reduce performance.\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 2",
   "language": "python",
   "name": "python2"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.5.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 1
}
